r"""items.py
    
    This module is just the definition of the NFLPlayer item our spider captures.
"""
from scrapy.item import Item, Field

# pylint: disable=too-many-ancestors
class NFLPlayer(Item):
    """
        This is the class for encapsulating a player record and its fields.
    """
    acceleration = Field()
    age = Field()
    agility = Field()
    awareness = Field()
    birthdate = Field()
    break_tackle = Field()
    breathing_strip = Field()
    carrying = Field()
    catching = Field()
    college = Field()
    contract_length = Field()
    contract_years_left = Field()
    draft_pick = Field()
    draft_round = Field()
    elusiveness = Field()
    eye_black = Field()
    face_id = Field()
    face_mask = Field()
    first_name = Field()
    hair_color = Field()
    hair_style = Field()
    handedness = Field()
    height = Field()
    helmet = Field()
    injury = Field()
    jersey_number = Field()
    jumping = Field()
    kick_accuracy = Field()
    kick_power = Field()
    kick_return = Field()
    last_name = Field()
    left_elbow = Field()
    left_hand = Field()
    left_knee = Field()
    left_shoe = Field()
    left_wrist = Field()
    mouthpiece = Field()
    neck_pad = Field()
    nfl_icon = Field()
    pass_block = Field()
    pass_block_power = Field()
    pass_block_finesse = Field()
    playaction = Field()
    pro_bowl = Field()
    position = Field()
    right_elbow = Field()
    right_hand = Field()
    right_knee = Field()
    right_shoe = Field()
    right_wrist = Field()
    role_one = Field()
    role_two = Field()
    run_block = Field()
    run_block_power = Field()
    run_block_finesse = Field()
    signing_bonus = Field()
    skin_color = Field()
    sleeves = Field()
    speed = Field()
    stamina = Field()
    strength = Field()
    tackle = Field()
    tattoo_left = Field()
    tattoo_right = Field()
    team = Field()
    tendency = Field()
    throw_accuracy_deep = Field()
    throw_accuracy_mid = Field()
    throw_accuracy_short = Field()
    throw_on_the_run = Field()
    throw_power = Field()
    total_salary = Field()
    toughness = Field()
    trucking = Field()
    visor = Field()
    weight = Field()
    years_pro = Field()
